Map mcColorCodes = {
  '§0': 0xFF000000,
  '§1': 0xFF0000AA,
  '§2': 0xFF00AA00,
  '§3': 0xFF00AAAA,
  '§4': 0xFFAA0000,
  '§5': 0xFFAA00AA,
  '§6': 0xFFFFAA00,
  '§7': 0xFFAAAAAA,
  '§8': 0xFF555555,
  '§9': 0xFF5555FF,
  '§a': 0xFF55FF55,
  '§b': 0xFF55FFFF,
  '§c': 0xFFFF5555,
  '§d': 0xFFFF55FF,
  '§e': 0xFFFFFF55,
  '§f': 0xFFFFFFFF,
};

Map colors = {
  'BLACK': '§0',
  'DARK_BLUE': '§1',
  'DARK_GREEN': '§2',
  'DARK_AQUA': '§3',
  'DARK_RED': '§4',
  'DARK_PURPLE': '§5',
  'GOLD': '§6',
  'GREY': '§7',
  'DARK_GREY': '§8',
  'BLUE': '§9',
  'GREEN': '§a',
  'AQUA': '§b',
  'RED': '§c',
  'LIGHT_PURPLE': '§d',
  'YELLOW': '§e',
  'WHITE': '§f',
};

List prestigeColors = [
  'GREY',
  'WHITE',
  'GOLD',
  'AQUA',
  'DARK_GREEN',
  'DARK_AQUA',
  'DARK_RED',
  'LIGHT_PURPLE',
  'BLUE',
  'DARK_PURPLE',
  ['RED', 'GOLD', 'YELLOW', 'GREEN', 'AQUA', 'LIGHT_PURPLE', 'DARK_PURPLE'],
  ['WHITE', 'GREY'],
  ['YELLOW', 'GOLD'],
  ['AQUA', 'DARK_AQUA'],
  ['GREEN', 'DARK_GREEN'],
  ['DARK_AQUA', 'BLUE'],
  ['RED', 'DARK_RED'],
  ['LIGHT_PURPLE', 'DARK_PURPLE'],
  ['BLUE', 'DARK_BLUE'],
  ['DARK_PURPLE', 'DARK_GREY'],
  ['DARK_GREY', 'GREY', 'WHITE', 'WHITE', 'GREY', 'GREY', 'DARK_GREY'],
  ['WHITE', 'WHITE', 'YELLOW', 'YELLOW', 'GOLD', 'GOLD', 'GOLD'],
  ['GOLD', 'GOLD', 'WHITE', 'WHITE', 'AQUA', 'DARK_AQUA', 'DARK_AQUA'],
  ['DARK_PURPLE', 'DARK_PURPLE', 'LIGHT_PURPLE', 'LIGHT_PURPLE', 'GOLD', 'YELLOW', 'YELLOW'],
  ['AQUA', 'AQUA', 'WHITE', 'WHITE', 'GREY', 'GREY', 'DARK_GREY'],
  ['WHITE', 'WHITE', 'GREEN', 'GREEN', 'DARK_GREEN', 'DARK_GREEN', 'DARK_GREEN'],
  ['DARK_RED', 'DARK_RED', 'RED', 'RED', 'LIGHT_PURPLE', 'LIGHT_PURPLE', 'DARK_PURPLE'],
  ['YELLOW', 'YELLOW', 'WHITE', 'WHITE', 'DARK_GREY', 'DARK_GREY', 'DARK_GREY'],
  ['GREEN', 'GREEN', 'DARK_GREEN', 'DARK_GREEN', 'GOLD', 'GOLD', 'YELLOW'],
  ['AQUA', 'AQUA', 'DARK_AQUA', 'DARK_AQUA', 'BLUE', 'BLUE', 'DARK_BLUE'],
  ['YELLOW', 'YELLOW', 'GOLD', 'GOLD', 'RED', 'RED', 'DARK_RED'],
];
